var searchData=
[
  ['s_20c_20test_20framework_0',['Welcome to &lt;strong&gt;GoogleTest&lt;/strong&gt;, Google&apos;s C++ test framework!',['../md_lib_2googletest-master_2_r_e_a_d_m_e.html#autotoc_md44',1,'']]],
  ['saveargaction_1',['SaveArgAction',['../structtesting_1_1internal_1_1_save_arg_action.html',1,'testing::internal']]],
  ['saveargpointeeaction_2',['SaveArgPointeeAction',['../structtesting_1_1internal_1_1_save_arg_pointee_action.html',1,'testing::internal']]],
  ['scopedprematureexitfile_3',['ScopedPrematureExitFile',['../classtesting_1_1internal_1_1_scoped_premature_exit_file.html',1,'testing::internal']]],
  ['scopedtrace_4',['ScopedTrace',['../classtesting_1_1_scoped_trace.html',1,'testing']]],
  ['separateinstancetest_5',['SeparateInstanceTest',['../class_separate_instance_test.html',1,'']]],
  ['sequencetestinglistener_6',['SequenceTestingListener',['../class_sequence_testing_listener.html',1,'']]],
  ['setargrefereeaction_7',['SetArgRefereeAction',['../structtesting_1_1internal_1_1_set_arg_referee_action.html',1,'testing::internal']]],
  ['setargumentpointeeaction_8',['SetArgumentPointeeAction',['../structtesting_1_1internal_1_1_set_argument_pointee_action.html',1,'testing::internal']]],
  ['setarrayargumentaction_9',['SetArrayArgumentAction',['../structtesting_1_1internal_1_1_set_array_argument_action.html',1,'testing::internal']]],
  ['setenvvar_10',['SetEnvVar',['../namespacegtest__test__utils.html#abece99ff6c6b9c882ab12c15793898bf',1,'gtest_test_utils']]],
  ['seterrnoandreturnaction_11',['SetErrnoAndReturnAction',['../classtesting_1_1internal_1_1_set_errno_and_return_action.html',1,'testing::internal']]],
  ['setup_12',['setUp',['../classgoogletest-filter-unittest_1_1_g_test_filter_unit_test.html#a80e82b6c777fbbf575ad83cb8d2ae56c',1,'googletest-filter-unittest::GTestFilterUnitTest']]],
  ['setup_13',['Setup',['../md_lib_2googletest-master_2googletest_2_r_e_a_d_m_e.html#autotoc_md28',1,'']]],
  ['setupenvironment_14',['SetupEnvironment',['../class_setup_environment.html',1,'']]],
  ['setupfailtest_15',['SetupFailTest',['../class_setup_fail_test.html',1,'']]],
  ['setuptestcasetest_16',['SetUpTestCaseTest',['../classtesting_1_1_set_up_test_case_test.html',1,'testing']]],
  ['setuptestsuitetest_17',['SetUpTestSuiteTest',['../classtesting_1_1_set_up_test_suite_test.html',1,'testing']]],
  ['shared_20library_20dll_18',['As a Shared Library (DLL)',['../md_lib_2googletest-master_2googletest_2_r_e_a_d_m_e.html#autotoc_md36',1,'']]],
  ['skipentireenvironmenttest_19',['SkipEntireEnvironmentTest',['../classgtest__skip__check__output__test_1_1_skip_entire_environment_test.html',1,'gtest_skip_check_output_test.SkipEntireEnvironmentTest'],['../classgtest__skip__environment__check__output__test_1_1_skip_entire_environment_test.html',1,'gtest_skip_environment_check_output_test.SkipEntireEnvironmentTest']]],
  ['skippedtest_20',['SkippedTest',['../class_skipped_test.html',1,'']]],
  ['soon_21',['Coming Soon',['../md_lib_2googletest-master_2_r_e_a_d_m_e.html#autotoc_md43',1,'']]],
  ['source_20projects_22',['Related Open Source Projects',['../md_lib_2googletest-master_2_r_e_a_d_m_e.html#autotoc_md52',1,'']]],
  ['stackinterface_23',['StackInterface',['../classtesting_1_1gmock__function__mocker__test_1_1_stack_interface.html',1,'testing::gmock_function_mocker_test']]],
  ['standalone_20cmake_20project_24',['Standalone CMake Project',['../md_lib_2googletest-master_2googletest_2_r_e_a_d_m_e.html#autotoc_md30',1,'']]],
  ['standard_20version_25',['C++ Standard Version',['../md_lib_2googletest-master_2googletest_2_r_e_a_d_m_e.html#autotoc_md33',1,'']]],
  ['started_26',['Getting Started',['../md_lib_2googletest-master_2_r_e_a_d_m_e.html#autotoc_md45',1,'']]],
  ['statefulnamingfunctor_27',['StatefulNamingFunctor',['../struct_stateful_naming_functor.html',1,'']]],
  ['statefulnamingtest_28',['StatefulNamingTest',['../class_stateful_naming_test.html',1,'']]],
  ['static_20runtimes_29',['Visual Studio Dynamic vs Static Runtimes',['../md_lib_2googletest-master_2googletest_2_r_e_a_d_m_e.html#autotoc_md32',1,'']]],
  ['staticasserttypeeqtesthelper_30',['StaticAssertTypeEqTestHelper',['../class_static_assert_type_eq_test_helper.html',1,'']]],
  ['stlcontainerview_31',['StlContainerView',['../classtesting_1_1internal_1_1_stl_container_view.html',1,'testing::internal']]],
  ['stlcontainerview_3c_20_3a_3astd_3a_3atuple_3c_20elementpointer_2c_20size_20_3e_20_3e_32',['StlContainerView&lt; ::std::tuple&lt; ElementPointer, Size &gt; &gt;',['../classtesting_1_1internal_1_1_stl_container_view_3_01_1_1std_1_1tuple_3_01_element_pointer_00_01_size_01_4_01_4.html',1,'testing::internal']]],
  ['stlcontainerview_3c_20element_5bn_5d_3e_33',['StlContainerView&lt; Element[N]&gt;',['../classtesting_1_1internal_1_1_stl_container_view_3_01_element_0f_n_0e_4.html',1,'testing::internal']]],
  ['streamableinglobal_34',['StreamableInGlobal',['../class_streamable_in_global.html',1,'']]],
  ['streamabletemplateinfoo_35',['StreamableTemplateInFoo',['../classfoo_1_1_streamable_template_in_foo.html',1,'foo']]],
  ['streamprinter_36',['StreamPrinter',['../structtesting_1_1internal_1_1internal__stream__operator__without__lexical__name__lookup_1_1_stream_printer.html',1,'testing::internal::internal_stream_operator_without_lexical_name_lookup']]],
  ['strictmock_37',['StrictMock',['../classtesting_1_1_strict_mock.html',1,'testing']]],
  ['strictmockimpl_38',['StrictMockImpl',['../classtesting_1_1internal_1_1_strict_mock_impl.html',1,'testing::internal']]],
  ['strictmockimpl_3c_20mockclass_20_3e_39',['StrictMockImpl&lt; MockClass &gt;',['../classtesting_1_1internal_1_1_strict_mock_impl.html',1,'testing::internal']]],
  ['string_40',['String',['../classtesting_1_1internal_1_1_string.html',1,'testing::internal']]],
  ['strong_20googletest_20strong_20google_20s_20c_20test_20framework_41',['Welcome to &lt;strong&gt;GoogleTest&lt;/strong&gt;, Google&apos;s C++ test framework!',['../md_lib_2googletest-master_2_r_e_a_d_m_e.html#autotoc_md44',1,'']]],
  ['studio_20dynamic_20vs_20static_20runtimes_42',['Visual Studio Dynamic vs Static Runtimes',['../md_lib_2googletest-master_2googletest_2_r_e_a_d_m_e.html#autotoc_md32',1,'']]],
  ['style_43',['Style',['../md_lib_2googletest-master_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md6',1,'']]],
  ['submit_20your_20own_20code_44',['How to become a contributor and submit your own code',['../md_lib_2googletest-master_2_c_o_n_t_r_i_b_u_t_i_n_g.html',1,'']]],
  ['subprocess_45',['Subprocess',['../classgtest__test__utils_1_1_subprocess.html',1,'gtest_test_utils']]],
  ['successfultest_46',['SuccessfulTest',['../class_successful_test.html',1,'']]],
  ['suiteapiresolver_47',['SuiteApiResolver',['../structtesting_1_1internal_1_1_suite_api_resolver.html',1,'testing::internal']]],
  ['sumof5functor_48',['SumOf5Functor',['../structtesting_1_1gmock__more__actions__test_1_1_sum_of5_functor.html',1,'testing::gmock_more_actions_test']]],
  ['sumof6functor_49',['SumOf6Functor',['../structtesting_1_1gmock__more__actions__test_1_1_sum_of6_functor.html',1,'testing::gmock_more_actions_test']]],
  ['support_20features_50',['Underlying library support features',['../md_lib_2googletest-master_2googletest_2include_2gtest_2internal_2custom_2_r_e_a_d_m_e.html#autotoc_md24',1,'']]],
  ['supported_20platforms_51',['Supported Platforms',['../md_lib_2googletest-master_2_r_e_a_d_m_e.html#autotoc_md47',1,'']]],
  ['symbols_3a_52',['Exporting API symbols:',['../md_lib_2googletest-master_2googletest_2include_2gtest_2internal_2custom_2_r_e_a_d_m_e.html#autotoc_md25',1,'']]],
  ['systems_53',['Systems',['../md_lib_2googletest-master_2_r_e_a_d_m_e.html#autotoc_md50',1,'Build Systems'],['../md_lib_2googletest-master_2_r_e_a_d_m_e.html#autotoc_md48',1,'Operating Systems']]]
];
